#include <iostream>
#define A 
#define AA using
#define AAA namespace
#define AAAA std
#define AAAAA ;
#define AAAAAA int
#define AAAAAAA main
#define AAAAAAAA ()
#define AAAAAAAAA {
#define AAAAAAAAAA n
#define AAAAAAAAAAA ,
#define AAAAAAAAAAAA i
#define AAAAAAAAAAAAA bool
#define AAAAAAAAAAAAAA isPrime
#define AAAAAAAAAAAAAAA =
#define AAAAAAAAAAAAAAAA true;
#define AAAAAAAAAAAAAAAAA cout
#define AAAAAAAAAAAAAAAAAA <<
#define AAAAAAAAAAAAAAAAAAA "Enter a positive integer: ";
#define AAAAAAAAAAAAAAAAAAAA cin
#define AAAAAAAAAAAAAAAAAAAAA >>
#define AAAAAAAAAAAAAAAAAAAAAA n;
#define AAAAAAAAAAAAAAAAAAAAAAA for
#define AAAAAAAAAAAAAAAAAAAAAAAA (
#define AAAAAAAAAAAAAAAAAAAAAAAAA 2
#define AAAAAAAAAAAAAAAAAAAAAAAAAA <=
#define AAAAAAAAAAAAAAAAAAAAAAAAAAA /
#define AAAAAAAAAAAAAAAAAAAAAAAAAAAA ++i
#define AAAAAAAAAAAAAAAAAAAAAAAAAAAAA )
#define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA if
#define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA %
#define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ==
#define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0
#define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA false
#define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA break
#define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA }
#define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA " is a prime number"
#define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA else
#define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA " is not a prime number"
#define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA return
A 
AA AAA AAAA AAAAA 
A 
AAAAAA AAAAAAA AAAAAAAA AAAAAAAAA 
AAAAAA AAAAAAAAAA AAAAAAAAAAA AAAAAAAAAAAA AAAAA 
AAAAAAAAAAAAA AAAAAAAAAAAAAA AAAAAAAAAAAAAAA AAAAAAAAAAAAAAAA 
AAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAA 
AAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAA 
AAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAA AAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAA AAAAA AAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAA AAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAA 
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAA 
AAAAAAAAAAAAAA AAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAA 
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAA 
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAA 
AAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAA AAAAAAAAAA AAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAA 
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 
AAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAA AAAAAAAAAA AAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAA 
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAA 
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 
