#include <iostream>
#define A using
#define AA namespace
#define AAA std;
#define AAAA int
#define AAAAA main()
#define AAAAAA {
#define AAAAAAA n
#define AAAAAAAA ,
#define AAAAAAAAA i;
#define AAAAAAAAAA bool
#define AAAAAAAAAAA isPrime
#define AAAAAAAAAAAA =
#define AAAAAAAAAAAAA true;
#define AAAAAAAAAAAAAA cout
#define AAAAAAAAAAAAAAA <<
#define AAAAAAAAAAAAAAAA "Enter a positive integer: "
#define AAAAAAAAAAAAAAAAA ;
#define AAAAAAAAAAAAAAAAAA cin
#define AAAAAAAAAAAAAAAAAAA >>
#define AAAAAAAAAAAAAAAAAAAA n;
#define AAAAAAAAAAAAAAAAAAAAA for
#define AAAAAAAAAAAAAAAAAAAAAA (
#define AAAAAAAAAAAAAAAAAAAAAAA i
#define AAAAAAAAAAAAAAAAAAAAAAAA 2
#define AAAAAAAAAAAAAAAAAAAAAAAAA <=
#define AAAAAAAAAAAAAAAAAAAAAAAAAA /
#define AAAAAAAAAAAAAAAAAAAAAAAAAAA ++i
#define AAAAAAAAAAAAAAAAAAAAAAAAAAAA )
#define AAAAAAAAAAAAAAAAAAAAAAAAAAAAA if
#define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA %
#define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ==
#define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0
#define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA false
#define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA break
#define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA }
#define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA " is a prime number"
#define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA else
#define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA " is not a prime number"
#define AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA return
A AA AAA 
AAAA AAAAA AAAAAA 
AAAA AAAAAAA AAAAAAAA AAAAAAAAA 
AAAAAAAAAA AAAAAAAAAAA AAAAAAAAAAAA AAAAAAAAAAAAA 
AAAAAAAAAAAAAA AAAAAAAAAAAAAAA AAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAA 
AAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAA 
AAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAA 
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAA AAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAA 
AAAAAAAAAAA AAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAA 
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAA 
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 
AAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAA 
AAAAAAAAAAAAAA AAAAAAAAAAAAAAA AAAAAAA AAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAA 
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 
AAAAAAAAAAAAAA AAAAAAAAAAAAAAA AAAAAAA AAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAA 
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA AAAAAAAAAAAAAAAAA 
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 
